---
- hosts: local
  connection: local
  gather_facts: false
  vars:
    idempotency_id: 'idempotency_id_2'
    keypair_local_path: /Users/amaury/.ssh/id_rsa.hackathon
    keypair_local_pub_path: /Users/amaury/.ssh/id_rsa.hackathon.pub
    keypair: ansible-amaury
    instances:
      name: Xtreme-orient
      ami: ami-d130e6a6
      type: m1.small
      count: 1
      security_group:
        name: "orient-cluster"
        description: "orientdb cluster for benchmarks"
        rules:
          - { proto: tcp, from_port: 22, to_port: 22, cidr_ip: 0.0.0.0/0 }
  tasks:
    - name: Keypair is ok
      local_action:
        module: ec2_key
        name: "{{keypair}}"
        key_material: "{{ item }}"
      with_file: keypair_local_pub_path

    - name: Security group is ok
      local_action:
        module: ec2_group
        name: "{{ instances.security_group.name }}"
        description: "{{ instances.security_group.description }}"
        rules: "{{instances.security_group.rules}}"

    - name: spawn master instances
      local_action:
        module: ec2
        key_name: "{{ keypair }}"
        instance_type: "{{ instances.type }}"
        group: "{{ instances.security_group.name }}"
        instance_tags:
          Name: "{{ instances.name }}"
          ClusterRole: "master"
        image: "{{ instances.ami }}"
        wait: yes
        count: "{{ instances.count }}"
        id: "{{ idempotency_id }}"
      register: ec2master

    - name: Add new instance to ansible host group
      local_action: add_host hostname={{ item.public_ip }} groupname=orient_cluster_master
      with_items: ec2master.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
      with_items: ec2master.instances

- hosts: orient_cluster_master
  user: admin
  sudo: true
  vars:
    ansible_ssh_private_key_file: /Users/amaury/.ssh/id_rsa.hackathon
  tasks:
    - include: orientdb.yml
      vars:
        orient:
          user: orientdb
          randomPasswordSeed: MyRandomSeeeed